### ISSUE TITLE
How to use this library?

### ISSUE THREAD

**Issue by yashwp** [dfa1234/ngx-image-compress#1]
`import {ImageCompress} from "ngx-image-compress";
// To get your image data source string (aka "data:image/jpeg:base64...")
ImageCompress.uploadFile(...)
// To start the compression
ImageCompress.compress(...)`

This is the only thing given in your doc. But I want to know how can I use this? Can you post a working example with `<input type="file">`

**Comment by dfa1234** [comment]
Hi, 
The code is working but I need  to finish the packaging on this one.
I will try on this week, that is a very usefull library.

**Comment by yashwp** [comment]
@dfa1234 Just a suggestion, while publishing the library please provide the usage example in simple language... That will be great... 
Thanks for the ack. 👍

**Comment by ClaudioKirchmair** [comment]
Just take the 5 min of your time and post a working example. Then you can finish the packaging ;)

**Comment by dfa1234** [comment]
It's done
I edited the readme also.
You all are welcome.
You can still use the same version from npm anyway.
Maybe I will make a future release on npm with some breaking changes (be sure to keep the 1.0.2).
I don't like how the library is working actually, but it's working (you can test it with the project I just added in the repo)

**Comment by dfa1234** [comment]
Ho with angular 6 the packaging is no more valid.
For now just use the content of index.ts in your code and it will work
I will make another package soon

**Comment by jafsparrow** [comment]
Really...!! you have put some efforts do to this, why can't you make a sample without confusion. If you could let me know the process, I will make the example..

**Comment by dfa1234** [comment]
The sample is in the `tests` directory, did you find it?
