### ISSUE TITLE
Require Angular 16?

### ISSUE THREAD

**Issue by anh-rivergon** [dfa1234/ngx-image-compress#105]
Looks like Angular 16 is required. Is this the intention?

npm ERR! Found: @angular/core@15.2.9
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"^15.2.9" from the root project
npm ERR!   peer @angular/core@">= 9" from ngx-image-compress@13.1.16
npm ERR!   node_modules/ngx-image-compress
npm ERR!     ngx-image-compress@"^13.1.16" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"16.0.0" from @angular/common@16.0.0
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@">= 9" from ngx-image-compress@13.1.16
npm ERR!   node_modules/ngx-image-compress
npm ERR!     ngx-image-compress@"^13.1.16" from the root project

**Comment by dfa1234** [comment]
No it's not the intention, that's because angular 16 have been released today.
It will be take of soon

**Comment by dfa1234** [comment]
Done
