### ISSUE TITLE
Compress Image with Max Size without use upload

### ISSUE THREAD

**Issue by pj-alvarado10** [dfa1234/ngx-image-compress#107]
I need to compress an image and get compressed image with a max size. I have the image uploaded before, then I can not use `uploadAndGetImageWithMaxSize()`, then I use directly the function `compressFile()` but the last one doesn't have the option to put a max size like function parameter. 

Is there a way to just call the file compression function but with a maximum final file size, without calling an upload function?

Thank you.

**Comment by LCseniordev** [comment]
Same for me. We have a dropzone and then crop functionality before compression. 

Can you please advice on how to achieve Max Size compression in that flow?

Thanks in advance!

**Comment by dfa1234** [comment]
The only complication is to define what will be the input for the this compress function. If the upload is done externally, or using the upload function from the library? Maybe we need to support both

**Comment by mer30boy** [comment]
I also have a similar need. After uploading the photo, we perform a series of different processing operations and finally we need to compress it to the maximum size.
When do you think this feature will be available?
Thanks in advance!

**Comment by jaimink** [comment]
Waiting for this feature update. Any estimated timeline?

**Comment by dfa1234** [comment]
> Waiting for this feature update. Any estimated timeline?

It's asked multiple times, so let say by the end of the week

**Comment by webdevrepo** [comment]
> > Waiting for this feature update. Any estimated timeline?
> 
> It's asked multiple times, so let say by the end of the week

Looking forward to hear an update on this..

**Comment by dfa1234** [comment]
missed last time. this week.

**Comment by webdevrepo** [comment]
@dfa1234 anything new

**Comment by webdevrepo** [comment]
Hey David, @dfa1234 anything new now. Im sure you have a lot of things to do, but it would be really great to see an update here.

**Comment by dfa1234** [comment]
Yes this is in progress and published by today

On 22 Jul 2024, at 6:42, Nand ***@***.***> wrote:

﻿

Hey David, @dfa1234<https://github.com/dfa1234> anything new now. Im sure you have a lot of things to do, but it would be really great to see an update here.

**Comment by dfa1234** [comment]
COde is being published. If someone in the thread feel like helping, please raise a flag is anything broke or something, I went on "yolo mode" for this one, with little test to speed up.
