### ISSUE TITLE
ERROR Error: Uncaught (in promise): Event: {"isTrusted":true}

### ISSUE THREAD

**Issue by kinizumi** [dfa1234/ngx-image-compress#108]
Got ERROR Error: Uncaught (in promise): Event: {"isTrusted":true}
when calling 'this.imageCompress    .compressFile.....'

**Comment by WellingtonBraga** [comment]
Hello everyone,

Do we have any news about this? 

Regards,

**Comment by WellingtonBraga** [comment]
Hi guys,

Anything new on this?

**Comment by dfa1234** [comment]
We need more info. Fork this and give us the issue: https://stackblitz.com/edit/ngx-image-compress

**Comment by kinizumi** [comment]
never mind switched to use image-conversion instead
