### ISSUE TITLE
Image turn black after Compression

### ISSUE THREAD

**Issue by arslanali143** [dfa1234/ngx-image-compress#111]
Issue happening only in tablets after upgrade to Angular 14 to 16 & Browser Upgrade from Firefox 78 to 119.

**Comment by dfa1234** [comment]
Same as https://github.com/dfa1234/ngx-image-compress/issues/84

Please give us your package json and some code to investigate

**Comment by dfa1234** [comment]
You need to do this: https://stackblitz.com/edit/ngx-image-compress-ionic
