### ISSUE TITLE
Show spinner or loading circle while it compresses a slightly large file

### ISSUE THREAD

**Issue by umoruj** [dfa1234/ngx-image-compress#14]
I would like to show a spinner that indicates the file is being compressed. how would I achieve that,  as putting it before the 'this.imageCompress.uploadFile()' prevents me from stopping the spinner if the user cancels the operation. And putting it inside the 'then' block kind of defeats the purpose as it takes a little while before it actually proceeds to the 'then' block. Thanks for your help.

`  compressFile() {
  
    this.isloading = true;
    this.imageCompress.uploadFile().then(({image, orientation}) => {
    
      this.imgResultBeforeCompress = image;
      console.warn('Size in bytes was:', this.imageCompress.byteCount(image));
      
      this.imageCompress.compressFile(image, orientation, 75, 50).then(
        result => {
          this.isloading = false;
          console.log(result);
          this.imgResultAfterCompress = result;
          console.warn('Size in bytes is now:', this.imageCompress.byteCount(result));
        }
      );
      
    });
    
  }`

**Comment by dfa1234** [comment]
Do not set isLoading before uploadFile, it doesn't make sense.
`imageCompress.uploadFile` very quick, in fact it doesn't upload anything. It just open the select file window.
(maybe I should change the name of this function)
put isLoading only before `imageCompress.compressFile`
