### ISSUE TITLE
Sometime uploadFile().then() function does not fire

### ISSUE THREAD

**Issue by casper5822** [dfa1234/ngx-image-compress#18]
Hello,
i have an angular 8 app with this simple button (as written in your example) :

` <button class="ng2-file-input-drop-container" (click)="selectedImage()">{{browseText}}</button>`
and the method: 

`public selectedImage() {

     this.imageCompress.uploadFile()
     .then(
       ({image, orientation}) => {...})`

There are some cases  where the promise then function is not called.
It is not clear when it happens, because it seems a random issue.

Maybe it could be related to the Promise resolve.

The problem happens both in Chrome and Firefox, latest versions. 

In same places i read something about zone.js and FileReader().onload event that doesn't work properly. Maybe can be usefull.

Best regards
Antonio.

**Comment by dfa1234** [comment]
Do you think it's this problem?
https://stackoverflow.com/questions/44091937/why-is-this-filereader-onload-not-firing
Chrome seem to have fixed that

**Comment by midhunjohnson7** [comment]
@dfa1234  can you explain the logic you have used in getOrientation function.
Thanks in advance.

**Comment by dfa1234** [comment]
@midhunjohnson7 you can check the new version with a getOrientation function from the service
Also getOrientation is very simple, it's a EXIF reading for getting the information from the picture (typically if it was a picture from a smartphone). There is "no need" to understand that :)
