### ISSUE TITLE
Expose getOrientation api publically

### ISSUE THREAD

**Issue by dksb** [dfa1234/ngx-image-compress#26]
I use compress method directly and don't use your upload method. If you can make your getOrientation method available in the api it will be great.

**Comment by sheshaj** [comment]
Yes I agree with this. This library works perfectly when we are using <button> but if we are using <input type="file" accept="image/*"> element, then we don't need to use the uploadFile() function. In that case, we will not be getting the orientation of the image. So it would be better if we can expose the getOrientation function separately.

**Comment by dfa1234** [comment]
PR merged and available in npm from version `11.0.3`
