### ISSUE TITLE
error log wrong orientation value

### ISSUE THREAD

**Issue by DananJoy** [dfa1234/ngx-image-compress#3]
sir,

i had an issue with your default config.
when i'm trying to use the compression function it works well.
but got an error output log 'Wrong orientation value'

what shoud i do ?

i'm using angular 5 btw, with serverside rendering configuration.

thanks before sir.

**Comment by dfa1234** [comment]
No problem, it's a normal message, you have no orientation value, that's all.
It should be a warning, not an error message.

**Comment by dfa1234** [comment]
console log have been cleared
