### ISSUE TITLE
Resize the image

### ISSUE THREAD

**Issue by jeremytrigano** [dfa1234/ngx-image-compress#31]
Hello,
(don't know if it can be an "issue")
Could you, please, think about adding a method (or compressFile method parameters)  which can resize (increase/decrease pixels) the image ?

Update 1: ratio parameter isn't really convenient if I wish to resize to exactly 100px an image, for example
Thank you

**Comment by dfa1234** [comment]
It's a very good idea. Not in the agenda for the moment.

**Comment by dfa1234** [comment]
Done in version 13+
