### ISSUE TITLE
vector style PNG compressed to bigger size

### ISSUE THREAD

**Issue by vivizth** [dfa1234/ngx-image-compress#36]
Most vector style PNG result in bigger size after compressed. 

example files below compressed with
imageCompress.compressFile(res.image, res.orientation, 40, 100):
![download](https://user-images.githubusercontent.com/830114/94102562-9e081e80-fe5c-11ea-8fb6-4ff975ab73de.png)
Before compress: 4922 byte
After compress: 7118 byte

![download](https://user-images.githubusercontent.com/830114/94102599-b2e4b200-fe5c-11ea-950d-513b0547ae72.png)
Before compress: 9342 byte
After compress: 12330 byte
![compressed](https://user-images.githubusercontent.com/830114/94106317-60f45a00-fe65-11ea-92a6-360dfdbe8376.png)

**Comment by dfa1234** [comment]
There is nothing you can do.
Vector images are always better for the size.
Compressing will produce the image pixel by pixel and will lost the vector structure.
It's like zipping a zip file; try it, it will get bigger.
Eventually you could try to reduce the size.
