### ISSUE TITLE
compressing with mozzila android

### ISSUE THREAD

**Issue by mradmrad** [dfa1234/ngx-image-compress#38]
Hello , 

compressing pictures works with chrome (android) but not with firefox (android) for pictures more than 1.5 Mo

Thanks

**Comment by dfa1234** [comment]
please explain what happen by "not working"

**Comment by mradmrad** [comment]
for example for this link : 

https://stackblitz.com/edit/ngx-compress-sample

not working with firefox android

**Comment by dfa1234** [comment]
I inspected and it seem it's a problem specific with stackbiltz on firefox
There is many error linked to CORS policies, like this:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://c.staticblitz.com/assets/preview-d66a4ad1aa964283dc71b.js. (Reason: CORS request did not succeed).
```
We need to put the project on firebase or something, to verify if it's working

**Comment by mradmrad** [comment]
ok , thank you

**Comment by dfa1234** [comment]
Meanwhile I wil close this. If you meet the problem on android, with you own site or something, feel free to  post another detailled issue

**Comment by adamk22** [comment]
I'm running into a similar issue with Firefox on Android. Apparently, larger files 3-4MB's will cause the app to remain in a 'stuck' state because the compression somehow doesn't work (it doesn't resolve or reject the promise). 

In the case below, both logs will not get outputted because the promise doesn't resolve or reject:

```
async compressImage(file: string, fileSource: File): Promise<void | File> {
    const orientation = await this.imgCompress.getOrientation(fileSource);
    return this.imgCompress
		.compressFile(file, orientation, 50, 50)
		.then((image) => {
                         console.log('image', image);
			const imageBlob = this.dataURItoBlob(image.split(',')[1]);
			const imageFile = new File([imageBlob], fileSource.name, {
				type: 'image/jpeg',
			});
			return imageFile;
		 })
                 .catch((err: any) => {
                     console.log('err compress', err);
                  })
	}
```
