### ISSUE TITLE
problem during migration to angular 9

### ISSUE THREAD

**Issue by aminesafi8** [dfa1234/ngx-image-compress#39]
Hi folks,

The ngx-image-compress library works fine with **Angular 8,** but I was trying to migrate our project to **Angular 9** and I faced a lot of problems, I tried all the new versions of the library and the result was not as expected.
I also saw another issue similar to mine in this link [Please update to support Angular 9](https://github.com/dfa1234/ngx-image-compress/issues/22)
Could you please update to support Angular 9?

Thanks.

**Comment by dfa1234** [comment]
The library is already ready for Angular 11
Please provide here the errors you got with angular 9

**Comment by aminesafi8** [comment]
I have deleted the dependency from the **package.json** , the migration to angular 9 was successful, I also migrated to Angular 10 without the dependency and everything works fine, at this level, I returned back the dependency to migrate to Angular 11, and it was the big surprise too, I had the same issues, you find attached a screen shot of the problem (regardless of the angular version since I had the same problem with the version 9,10 and 11)
So I removed again the dependency, I migrated the project and I returned back later.
![capture](https://user-images.githubusercontent.com/25407983/101327526-1a60aa00-386f-11eb-84ea-3671c6fb2249.PNG)

**Comment by dfa1234** [comment]
Angular 9 10 and 11 are all supported.
I assume if you used the last library published, you would migrate without problem.
Anyway automatic migration are always problematic.
From your screenshot I can tell you was not on the last version, since the peerDependency is only 7.2.0, so it's an old version.

**Comment by aminesafi8** [comment]
> Angular 9 10 and 11 are all supported.
> I assume if you used the last library published, you would migrate without problem.
> Anyway automatic migration are always problematic.
> From your screenshot I can tell you was not on the last version, since the peerDependency is only 7.2.0, so it's an old version.

I'm using the latest version already, the problem was resolved as I explained earlier.
Thanks 👍
