### ISSUE TITLE
How to use it on input type file

### ISSUE THREAD

**Issue by thiagobraz** [dfa1234/ngx-image-compress#4]
Hello, i want to use this library to compress a image inserted by user in input type file. But i don`t understand in your documentation if this library is compatibility for this situation. Thank`s!

**Comment by dfa1234** [comment]
Yes it's totally relevant
I juste updated the readme, instructions are very clear.
You don't even need to create a `input`. Juste place a `button` with a `(click)` event using the `compressFile()` function, from the readme. Can't be more simple.

**Comment by thiagobraz** [comment]
Hm.. Ok. I not got it this just seeing the documentation. Maybe it's good to add an demo page to user see. Thank`s!

**Comment by dfa1234** [comment]
In fact reading the README you can find the demo 
take a look here: https://github.com/dfa1234/ngx-image-compress/blob/master/src/app/app.component.ts
