### ISSUE TITLE
Compressed size is larger than original size

### ISSUE THREAD

**Issue by weilies** [dfa1234/ngx-image-compress#40]
I have an issue here. How come the compressed size is larger than original? 
![Screenshot 2020-12-12 at 2 03 37 PM](https://user-images.githubusercontent.com/484828/101976708-e62c2580-3c82-11eb-9569-917dfa5686ea.png)

**Comment by dfa1234** [comment]
Indeed, it happen if you don't use a relevant image size ratio and quality.
Please try with several values.
If it's still not reducing as you expect, you can post here your ratio/quality and your image

**Comment by weilies** [comment]
Thanks for the promptly reply :)
