### ISSUE TITLE
Multiple Image compress

### ISSUE THREAD

**Issue by rushabhshah95** [dfa1234/ngx-image-compress#42]
How can I pass array of images blob to uploadfile function ? Could someone please provide me an idea/example to compress multiple file using ngx-image-compress?

**Comment by dfa1234** [comment]
If you look in the demo, there is 2 main function

`this.imageCompress.uploadFile` and  `this.imageCompress.compress`

Certainly we could adapt 'uploadFile' to your need, but currently it's only working for 1 file.

So you will need to implement this upload function for several file by yourself.

After that, you can write some kind of a loop and use `this.imageCompress.compress` multiple time

Good luck
