### ISSUE TITLE
Image compression fails on Firefox Android

### ISSUE THREAD

**Issue by adamk22** [dfa1234/ngx-image-compress#44]
I'm running into an issue with Firefox on Android (Related #38 ). Apparently, larger files 3-4MB's will cause the app to remain in a 'stuck' state because the compression somehow doesn't work (it doesn't resolve or reject the promise). 

In the case below, both `console.logs` will not get outputted because the promise doesn't resolve or reject:

```
async compressImage(file: string, fileSource: File): Promise<void | File> {
    const orientation = await this.imgCompress.getOrientation(fileSource);
    return this.imgCompress
		.compressFile(file, orientation, 50, 50)
		.then((image) => {
                         console.log('image', image);
			const imageBlob = this.dataURItoBlob(image.split(',')[1]);
			const imageFile = new File([imageBlob], fileSource.name, {
				type: 'image/jpeg',
			});
			return imageFile;
		 })
                 .catch((err: any) => {
                     console.log('err compress', err);
                  })
	}
```

Looking in the source code I noticed that in the `compress()` function the `onload` event won't fire when larger images are passed to the `compressFile()` function. Smaller images somehow work and the `onload` event is fired. I'm not sure why this is the case in firefox considering it works how it's suppose to work in Chrome (also with larger images).

**Comment by dfa1234** [comment]
Firefox android : small image are working but no more than 4 mb
Chrome android : every image is working

It's really a bummer, that seem some performance limitation specific to the phone OS.
Tested on Samsung and even 6mb is working here.
I let open meanwhile if other people have the same.

**Comment by dfa1234** [comment]
@adamk22  you can now use this link to make your performance tests

https://ngx-image-compress.web.app/

**Comment by dfa1234** [comment]
Tested on BrowerStack on a real device and it's working fine, with a image of 5mb.
Closing the issue

![image](https://user-images.githubusercontent.com/8502517/155216930-feee043f-b676-4679-b62a-9f7abcf54db6.png)
