### ISSUE TITLE
Increase the size when wanting to reduce the quality with the same ratio

### ISSUE THREAD

**Issue by AncaorDev** [dfa1234/ngx-image-compress#6]
Try to reduce the quality of an image with 100 of ratio and a quality of 50 and raised the weight of the image

**Comment by dfa1234** [comment]
please provide a sample, the original picture and the result picture

**Comment by AncaorDev** [comment]
> por favor proporcione una muestra, la imagen original y la imagen resultante

Example https://stackblitz.com/edit/ng2-example-rj6zg1

![image](https://user-images.githubusercontent.com/10332030/58924837-ff0d5f80-870a-11e9-9d3e-dd3fb155c9e2.png)

The image is : 
![wallhaven-lmwegp](https://user-images.githubusercontent.com/10332030/58924888-29f7b380-870b-11e9-8d46-1c8213e1ac92.png)

**Comment by dfa1234** [comment]
Thank for the stackblitz link.

I played a little with the parameters.
For 99, you go from 4824202 to **4484542**, you are under.
At 75 you reach 4824202 to **2374750**, less than a half.

You need to ajust the ratio according to your need.

**Comment by dfa1234** [comment]
I put the stackbilz link into the readme.
