### ISSUE TITLE
insufficient RAM memory

### ISSUE THREAD

**Issue by JonathanRamosNascimento** [dfa1234/ngx-image-compress#65]
sometimes when uploading an image it is consuming all the phone's memory and forcing to exit the app

**Comment by JonathanRamosNascimento** [comment]
![Sem título](https://user-images.githubusercontent.com/28025814/146557983-bdea351f-4fe7-487e-979c-8706a315e63a.png)

**Comment by dfa1234** [comment]
If you think it could be a limitation from the code and not the phone itself, you need to submit more specification about it.

I presume it's android.

So let's say which phone model, android version, and browser that you use there

**Comment by dfa1234** [comment]
Also look here if you use _stackblick https://github.com/dfa1234/ngx-image-compress/issues/44#issuecomment-848678744_

**Comment by dfa1234** [comment]
@JonathanRamosNascimento  you can now use this link to make your performance tests

https://ngx-image-compress.web.app/
