### ISSUE TITLE
I got the RangeError when I choose 0 size file

### ISSUE THREAD

**Issue by fluttercid** [dfa1234/ngx-image-compress#71]
Hello,
First of all, I appreciate your implementing this.
When I choose 0 size file on a selection dialog for the image, I got the RangeError as below.
![image](https://user-images.githubusercontent.com/65621167/150555582-a5dd8266-1ca4-499c-87ee-44b24e222afd.png)
Do you have any idea about it?
Thank you for your answer in advance.

**Comment by dfa1234** [comment]
Thank a lot to report some bug.

But I didn't succeed to reproduce.

What do you mean _"When I choose 0 size file on a selection dialog for the image"_?

Feel free to fork our [repo on stackblitz](https://stackblitz.com/edit/ngx-image-compress), save it, and and submit it here. I will take you just a couple of second.

**Comment by dfa1234** [comment]
@fluttercid I finally figured what you mean.

Indeed if you try to upload a totally empty file of 0 bytes, it will throws this error.

Thank for finding this interesting edge case 👍
