### ISSUE TITLE
StackBlitz uploadAndGetImageWithMaxSize doesn't work

### ISSUE THREAD

**Issue by Ranindu15** [dfa1234/ngx-image-compress#76]
Please update the stackblitz

**Comment by dfa1234** [comment]
Stackbliz a lot of new compilation problem not linked to this plugin. 
For your test please use [https://ngx-image-compress.web.app](https://ngx-image-compress.web.app/)

**Comment by Ranindu15** [comment]
@dfa1234  If I want to compress any image to lower than 150kb then how could I do this?

**Comment by dfa1234** [comment]
@Ranindu15 150kb is approximately .15mb, so you pass "0.15" to the function, it will do the work
