### ISSUE TITLE
File not uploading from android device

### ISSUE THREAD

**Issue by aviralgoyal** [dfa1234/ngx-image-compress#80]
Hi

I am currently working on a project in Angular 12. I used the function uploadAndGetImageWithMaxSize().
It works fine in the windows enviornment, the image gets uploaded and resized, but when I run it on an android device the upload dialog opens and select the image and press done, nothing happens. I'm not even getting any error codes or anything.

Is there a known issue for android devices?

**Comment by dfa1234** [comment]
I don't think there is an issue.
Please try to open this link with your android browser: https://image-library.app/
If you still have issues, please details your android specification and which browser you use.

**Comment by aviralgoyal** [comment]
You're correct it is working from the link you sent me, must be something in my code. I'll try adding some logging at each step to figure out the issue.

Also I wanted to know if there is a way to get the file name of the file uploaded from within the function.

**Comment by andresud** [comment]
I'm having the same issue using Ionic/Angular project, I can upload a photo from file but not from gallery nor from camera...  The app you passed is working fine.

**Comment by aviralgoyal** [comment]
@andresud I found the problem, in my case a used a mobile debugging option and when I'm using the Angular Material button, the library responds with a message, user interation is required, or something on those lines. I removed the angular button and now it works fine. @dfa1234  There is some kind of warning added to the library, which is behaving differently in case of an angular material type button.

There is one more enhancement that I would like to request, in the uploadAndGetImageWithMaxSize(), if you could expose the size and quality parameters to help the developer choose how much the size or quality should be reduced each time the loop runs for reducing the image size to the desired size. Right now it is set at 50%, which i feel is bit too much, I think it should be somewhere around 20% or user definable.

**Comment by dfa1234** [comment]
@aviralgoyal indeed we could add optional quality parameter. At first this function was done for being a lot more simple to use, with minimal configuration, when, on the contrary, this.compressImage give a lot more of control. But adding a optional parameter is not a problem. Feel free to submit some PR if you have some minutes so we will not forget it. even if the PR is not 100% ready it will help

**Comment by aviralgoyal** [comment]
@dfa1234  I will try my level best and find time, I am yet to make my first PR, so it might take me a while to read and understand, how to do this.

I tried upload a file < 1MB on [https://image-library.app/](https://image-library.app/)  
using the option Uploading, Compressing and returning with max size of 1 MegaByte.

It is giving an error as even though it is already smaller than 1mb. It is trying to reduce the file further and as it did not succeed and goes to the error handler instead of just succeeding without compressing.

**Comment by dfa1234** [comment]
@aviralgoyal interesting, indeed if image is already < to 1mb the promise should resolve and not reject, we will add a PR for this, or you can submit it, it can be a good exercise for you too :)

**Comment by dfa1234** [comment]
Filename available in #89
