### ISSUE TITLE
just compress and resize if width bigger than a given value

### ISSUE THREAD

**Issue by giammin** [dfa1234/ngx-image-compress#85]
I'm trying to achieve to just compress and resize if width bigger than a given value

something like:
```
const compressed = await this.imageResizerService.compressFile(
        blobInfo.blobUri(), DOC_ORIENTATION.Default,100, 80,this.config.maxWidth);
```

the compressed file is always bigger (filesize) than original file, is it normal?

**Comment by dfa1234** [comment]
@giammin  it's totally normal because you are using '100' in quality parameter.
If you don't decrease the quality even a little, it's very likely to happem
