### ISSUE TITLE
Get access to the File names

### ISSUE THREAD

**Issue by JoeBoxr** [dfa1234/ngx-image-compress#88]
Hello.

Excellent library.  Is there a way to get access to the File names when using:

this.imageCompress.uploadFile()
  .then((singleFile: { image: string, orientation: number }) => //...

Regards

**Comment by dfa1234** [comment]
Hi
It a work in progress
Like already stated in #80 
It will be available very soon

**Comment by dfa1234** [comment]
Done #89
