### ISSUE TITLE
Expose fileToDataURL Api publicaly

### ISSUE THREAD

**Issue by Gjuju** [dfa1234/ngx-image-compress#92]
Hello.
I use compress method directly and don't use your upload method, instead i use classic file input and a custom drag and drop directive.
So i must convert File to DataUrl before compressing it.

If you can make your fileToDataURL method available in the api it will be great and saves me to externalize your method.

best regards

EDIT // i forgot to mention that i use the legacy build in angular 9.

**Comment by dfa1234** [comment]
Please use now version `npm install ngx-image-compress@8.12.2`

I will give you want you need
