### ISSUE TITLE
`cannot contain special characters` error in the console, sometimes happening

### ISSUE THREAD

**Issue by aviralgoyal** [dfa1234/ngx-image-compress#93]
Hi David

When uploading file as per windows File size is 1.56 MB.

![image](https://user-images.githubusercontent.com/31591182/179493212-ba7c8476-32ec-4378-a307-3ee87002190a.png)

But on running Ngx Compress the byte count is coming at 10 MB.
In debug mode you can see the byte Count in yellow as 10.42

![image](https://user-images.githubusercontent.com/31591182/179493539-0ae4bfa3-df05-470f-a0c0-9948d2305af9.png)

I can send you the image for testing on your email. Please let me know, I don't want to upload it on public domain.

And it is giving this error on client side, which I can't reproduce.
`cannot contain special characters in <Path of file> for this file itself. I don't know the reason.

Can you please guide what seems to be the issue.

**Comment by dfa1234** [comment]
Hi @aviralgoyal can you send the image you used by mail dfaure123@gmail.com thank

**Comment by dfa1234** [comment]
@aviralgoyal anyway I think I know what is your problem already.
You used ratio=99 and  quality=100
First ratio 99 as not really any sense (but it's up to you)
But quality 100 is wrong. Your are compressing with 0% rate of loss in quality. That's can't happen. It will only increase the size.
Please use some realistic number (70 or 80 are very good quality already) Or anything bellow 100. 100 is a bad choice, maybe we could log some error for the user

**Comment by aviralgoyal** [comment]
@dfa1234 I've sent you the mail with the image. This problem is happening in very few images. So I don't think 99 is the issue. But do let me know if something else is amiss. Thank you in advance.

**Comment by dfa1234** [comment]
From the image you provided I see that an error is indeed throw.
So there is 2 different thing here:
 - First I repeat that using 100 or 99 quality ratio in jpeg transformation is not enough, it's very likely that you will get a jpeg bigger than the original message - this point is closed for me
 - Your image in particular is throwing an error and it's a problem that could be linked to the image (some defect in it). Or there is something happening in out code. So for this issue only, I marked the ticket to be investigated, we will look from where this error is throw to understand the issue
