### ISSUE TITLE
uploadFileOrReject not rejecting on Chrome on Android 

### ISSUE THREAD

**Issue by chaoranxie** [dfa1234/ngx-image-compress#94]
I tested out the `this.imageCompress.uploadFileOrReject()` on desktop, and when I dont select a file, the rejection is handled properly in `catch` block but when I tried the same thing in Chrome on android, the `catch` block is not executed at all.

**Comment by dfa1234** [comment]
@chaoranxie Like said in the read me, for test on mobile, use this url: https://image-library.app/

Stackblitz is just good to visualize the code but running the code have a lot of performance issue
