### ISSUE TITLE
Building a library alongside with Ivy and non-Ivy transpilation for retrocompatibility

### ISSUE THREAD

**Issue by arunreghu** [dfa1234/ngx-image-compress#95]
@davi01100100 @gethinoakes @dfa1234 @byronigoe @davi01100100   I am using ngx-image-compress-legacy plugin for my angular project(Angular verision 8) . Plugin works in local host when ng serve. but it throws error when trying to take production build(ng build --prod). 
`ERROR in ./src/app/admin/transactions/edit-transaction-modal.component.ngfactory.js
Module not found: Error: Can't resolve 'ngx-image-compress' in 'C:\angular\src\app\admin\transactions'`

I import 'NgxImageCompressService' in my component.ts and module file like following.
in component file
```
import { NgxImageCompressService } from ngx-image-compress-legacy;
constructor(){private imageCompress: NgxImageCompressService}
```

in module file
```
import {NgxImageCompressService} from "ngx-image-compress-legacy";
providers: [NgxImageCompressService]
```
Its Works in local(ng serve) but throw error in build(ng build --prod).

**Comment by arunreghu** [comment]
![Screenshot_32](https://user-images.githubusercontent.com/20110524/197124049-51290e10-2963-4385-859e-c3d12eae812a.png)

**Comment by nqdd** [comment]
I have the same problem

**Comment by bh** [comment]
Successfull workaround:

```patch
diff --git a/packages/app/tsconfig.json b/packages/app/tsconfig.json
index f9f9325..95e65ed 100644
--- a/packages/app/tsconfig.json
+++ b/packages/app/tsconfig.json
@@ -12,7 +12,8 @@
             ],
             "@ngxs/*": [
                 "./node_modules/@angular/*"
-            ]
+            ],
+            "ngx-image-compress": ["node_modules/ngx-image-compress-legacy"]
         },
     },
     "angularCompilerOptions": {

```

**Comment by heyjudemaldicas** [comment]
[dfa1234](https://github.com/dfa1234) any updates on this? encountering same issue.

**Comment by dfa1234** [comment]
@heyjudemaldicas  @bh @arunreghu  it's not impossible to fix this very soon, but it's somewhat complicated.
I don't want to work on 2 libraries.
So I would just package 1 library with the ivy compilation and the non-ivy.
But angular is not doing that out of the box.
Only solution would be to work on some script doing this for us.
I'm thinking a lot to do it soon, because supporting a very wide range of angular app is one of the goal of this library.

**Comment by FelipeCarriel** [comment]
I had the same error, solved it by changing the import in app.module

from
`import { NgxImageCompressService } from "ngx-image-compress-legacy"`

to
`import { NgxImageCompressService } from "ngx-image-compress-legacy/ngx-image-compress"`

**Comment by dfa1234** [comment]
This is done.

Please use 

npm install ngx-image-compress@8.12.2
