### ISSUE TITLE
File Object has to be emitted in the changeEvent like the traditional (onchange),,, to get the all file info..............

### ISSUE THREAD

**Issue by Vasanthvivi** [dfa1234/ngx-image-compress#96]
File Object has to be emitted in the changeEvent like the traditional (onchange),,, to get the all file info..............
it could be an enchancement....

**Comment by dfa1234** [comment]
Sure it could be, but we saw some opportunity to simplify the external API of our service,  and only return the relevant information (data-url, and file name).

What other property from the File object would be useful for your use case?

**Comment by Vasanthvivi** [comment]
the whole file object or atleast file name....

**Comment by Vasanthvivi** [comment]
similar to the file object in the input[type=file] formats....

**Comment by Vasanthvivi** [comment]
i hope you add and release within this week...

**Comment by dfa1234** [comment]
File name you already have it.
If you can explain what other properties from the object you need, that would be great.

**Comment by Vasanthvivi** [comment]
i didnt get the file name.. mostly if it emits the complete the file object that would be great....

**Comment by Vasanthvivi** [comment]
this.imageCompress.uploadAndGetImageWithMaxSize(1, true)    in this method  how to manually set the files.....

**Comment by Vasanthvivi** [comment]
@dfa1234  i mean the exact file name from the machine....

**Comment by Vasanthvivi** [comment]
change the label to enhancement

**Comment by Vasanthvivi** [comment]
hey man.... why there is no response....

**Comment by Vasanthvivi** [comment]
while compressing only am not getting the file name....

**Comment by dfa1234** [comment]
I think you will find what you need by browsing the source code. 
In particular this file
https://github.com/dfa1234/ngx-image-compress/blob/master/projects/ngx-image-compress/src/lib/image-compress.ts
It's were all the magic happen. Feel free to adapt any "upload" method you prefer
