### ISSUE TITLE
Ivy update

### ISSUE THREAD

**Issue by Dark0rion** [dfa1234/ngx-image-compress#97]
Will there be an update for ivy distribution?

![image](https://user-images.githubusercontent.com/13226108/208923010-a1192913-02d9-4035-a0b3-0d4b5a7feb75.png)

**Comment by dfa1234** [comment]
I'm not sure what is happening here
Compilation should be partial ivy
Like it's specify here
https://github.com/dfa1234/ngx-image-compress/blob/master/projects/ngx-image-compress/tsconfig.lib.prod.json
That will be investiguated. 
Could you share you package.json (only the dependency part)

**Comment by dfa1234** [comment]
Closing this issue, an continuing the discussion here: #95
